development:
  domain: localhost:3000
  s3_bucket_main: helpmecode_dev
  system_notification_email: no-reply@helpmeco.de

test:
  domain: test.host

production:
  domain: helpmeco.de
  s3_bucket_main: helpmecode

